services:
    api:
        container_name: nebula-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - .env
        restart: "no"
