POST http://localhost:8000/register
Content-Type: application/json

{
    "email": "tilen@test.com", 
    "name": "",
    "password": "a"
}

#{
#    "email": "admin@test.com", 
#    "password": "password123"
#}

### 